### ISSUE TITLE
Shiny package loading issues

### ISSUE THREAD

**Issue by elowell1** [Watts-College/cpp-526-sum-2023#5]
install.package("shiny") worked completely fine. But trying to call it from the library to use in the assignment resulted in this error: 

"> library(shiny)
Error: package or namespace load failed for ‘shiny’ in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]):
 namespace ‘rlang’ 1.0.5 is already loaded, but >= 1.0.6 is required
In addition: Warning message:
package ‘shiny’ was built under R version 4.2.3 

No updates are available and running "update.packages(ask = FALSE)" ends in updated packages but shiny still didn't work.
So. Kind of a bummer for the assignment

**Comment by lecy** [comment]
It looks like a package is locked during install. Try installing **rlang** from an R console (not R Studio). 

```r
install.packages( “rlang” )
```

**Comment by lecy** [comment]
Also, if you Google the error this is the first link you receive. 

https://community.rstudio.com/t/rlang-error-on-rstudio-2020-error-package-or-namespace-load-failed-for-in-loadnamespace/79768

It shows how to remove the old package before trying to install the fresh version.

You will encounter these types of problems on occasion with R since you have dozens of packages working together to solve problems. Understanding how to problem solve when you encounter errors is half of the skill set of data analytics.
